# Generated by Django 2.0 on 2018-02-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entorno', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FasePrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_de_prueba', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla', models.FileField(upload_to='GeneradorEvidencias/plantillas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(max_length=200)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('plan_pruebas', models.FileField(upload_to='GeneradorEvidencias/planes_de_prueba/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
                ('entorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Entorno')),
                ('fase_de_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.FasePrueba')),
            ],
        ),
    ]
