# Generated by Django 2.0 on 2018-02-09 11:24

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entorno', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FasePrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_de_prueba', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla', models.FileField(upload_to='GeneradorEvidencias/plantillas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(max_length=50)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('plan_de_pruebas', models.FileField(upload_to='GeneradorEvidencias/planes_de_prueba/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
                ('entorno', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cliente', chained_model_field='cliente', on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Entorno')),
                ('fase_de_prueba', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cliente', chained_model_field='cliente', on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.FasePrueba')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Plantilla')),
            ],
        ),
    ]
