# Generated by Django 2.0 on 2018-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaParaQuitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba_para_quitar', models.CharField(max_length=200)),
            ],
        ),
    ]
