# Generated by Django 2.0 on 2018-02-16 12:31

import GeneradorEvidencias.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0002_auto_20180212_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='plan_de_pruebas',
            field=models.FileField(blank=True, upload_to='GeneradorEvidencias/planes_de_prueba/', validators=[GeneradorEvidencias.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='plantilla',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Plantilla'),
        ),
    ]
