# Generated by Django 2.0 on 2018-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0002_casoprueba_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasoprueba',
            name='resultado_paso',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
