# Generated by Django 2.0 on 2018-02-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0002_pruebaparaquitar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PruebaParaQuitar',
        ),
    ]
