# Generated by Django 2.0 on 2018-02-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0003_delete_pruebaparaquitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='entorno',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fase_de_prueba',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
