# Generated by Django 2.0 on 2018-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0004_remove_solicitud_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='plan_de_pruebas',
            field=models.FileField(upload_to='GeneradorEvidencias/planes_de_prueba/'),
        ),
    ]
