# Generated by Django 2.0 on 2018-02-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0004_auto_20180205_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente')),
                ('entorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Entorno')),
                ('fase_de_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.FasePrueba')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Plantilla')),
            ],
        ),
    ]
