# Generated by Django 2.0 on 2018-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0005_auto_20180216_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='plan_de_pruebas',
            field=models.FileField(upload_to='planes_de_prueba/'),
        ),
    ]
