# Generated by Django 2.0 on 2018-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0005_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='solicitud',
            new_name='codigo_proyecto',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_proyecto',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
