# Generated by Django 2.0 on 2018-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0006_auto_20180206_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='plan_de_pruebas',
            field=models.FileField(default=0, upload_to='GeneradorEvidencias/planes_de_prueba/'),
            preserve_default=False,
        ),
    ]
