# Generated by Django 2.0 on 2018-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0006_auto_20180216_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_proyecto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='plan_de_pruebas',
            field=models.FileField(upload_to='GeneradorEvidencias/planes_de_prueba/'),
        ),
    ]
