# Generated by Django 2.0 on 2018-02-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0007_solicitud_plan_de_pruebas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entorno',
            name='entorno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigo_proyecto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_proyecto',
            field=models.CharField(max_length=50),
        ),
    ]
