# Generated by Django 2.0 on 2018-02-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0007_auto_20180216_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='planes_de_prueba')),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='plan_de_pruebas',
        ),
        migrations.AddField(
            model_name='planpruebas',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Solicitud'),
        ),
    ]
