# Generated by Django 2.0 on 2018-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0008_auto_20180219_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='planes_de_prueba')),
            ],
        ),
        migrations.RemoveField(
            model_name='planpruebas',
            name='solicitud',
        ),
        migrations.DeleteModel(
            name='PlanPruebas',
        ),
    ]
