# Generated by Django 2.0 on 2018-02-07 10:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0008_auto_20180206_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseprueba',
            name='cliente',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fase_de_prueba', chained_model_field='cliente', on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
        ),
    ]
