# Generated by Django 2.0 on 2018-02-07 10:45

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0009_auto_20180207_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faseprueba',
            name='cliente',
        ),
        migrations.AddField(
            model_name='faseprueba',
            name='cliente',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='fase_de_prueba', chained_model_field='cliente', to='GeneradorEvidencias.Cliente'),
        ),
    ]
