# Generated by Django 2.0 on 2018-02-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0010_planprueba_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprueba',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='plan_de_prueba',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.PlanPrueba'),
            preserve_default=False,
        ),
    ]
