# Generated by Django 2.0 on 2018-02-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0011_auto_20180219_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planprueba',
            old_name='docfile',
            new_name='archivo',
        ),
        migrations.RemoveField(
            model_name='planprueba',
            name='filename',
        ),
    ]
