# Generated by Django 2.0 on 2018-02-19 13:41

import GeneradorEvidencias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0012_auto_20180219_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprueba',
            name='archivo',
            field=models.FileField(upload_to='planes_de_prueba', validators=[GeneradorEvidencias.validators.validate_file_extension]),
        ),
    ]
