# Generated by Django 2.0 on 2018-02-07 11:01

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0012_auto_20180207_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faseprueba',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fase_de_prueba', chained_model_field='cliente', on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
        ),
    ]
