# Generated by Django 2.0 on 2018-02-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0013_auto_20180219_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='codigo_proyecto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre_proyecto',
        ),
        migrations.AddField(
            model_name='planprueba',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planprueba',
            name='codigo_proyecto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planprueba',
            name='nombre_proyecto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
