# Generated by Django 2.0 on 2018-02-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0013_auto_20180207_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseprueba',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entorno',
            name='entorno',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_proyecto',
            field=models.CharField(max_length=200),
        ),
    ]
