# Generated by Django 2.0 on 2018-02-20 12:27

import GeneradorEvidencias.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0014_auto_20180219_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprueba',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='plan_de_prueba',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(default=0, upload_to='planes_de_prueba', validators=[GeneradorEvidencias.validators.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='codigo_proyecto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_proyecto',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlanPrueba',
        ),
    ]
