# Generated by Django 2.0 on 2018-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0014_auto_20180207_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faseprueba',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='faseprueba',
            name='fase_de_prueba',
        ),
        migrations.AddField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=models.ManyToManyField(blank=True, to='GeneradorEvidencias.Cliente'),
        ),
    ]
