# Generated by Django 2.0 on 2018-02-07 13:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0015_auto_20180207_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faseprueba',
            name='fase_de_prueba',
        ),
        migrations.AddField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cliente', chained_model_field='cliente', default=0, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
            preserve_default=False,
        ),
    ]
