# Generated by Django 2.0 on 2018-02-07 13:15

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0016_auto_20180207_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseprueba',
            name='cliente',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cliente', chained_model_field='cliente', default=0, on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=models.CharField(max_length=50),
        ),
    ]
