# Generated by Django 2.0 on 2018-02-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0017_auto_20180207_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseprueba',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Cliente'),
        ),
        migrations.AlterField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=models.CharField(max_length=200),
        ),
    ]
