# Generated by Django 2.0 on 2018-02-07 13:19

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0018_auto_20180207_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faseprueba',
            name='cliente',
        ),
        migrations.AddField(
            model_name='faseprueba',
            name='cliente',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='cliente', chained_model_field='cliente', horizontal=True, to='GeneradorEvidencias.Cliente'),
        ),
        migrations.AlterField(
            model_name='faseprueba',
            name='fase_de_prueba',
            field=models.CharField(max_length=50),
        ),
    ]
