# Generated by Django 2.0 on 2018-02-08 08:57

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GeneradorEvidencias', '0020_auto_20180208_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='entorno',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cliente', chained_model_field='entorno', on_delete=django.db.models.deletion.CASCADE, to='GeneradorEvidencias.Entorno'),
        ),
    ]
